// Parses the Annex C table out of the bracket-logic markdown and generates
// lib/domain/annexC.ts. Validates each row (the 8 assigned 3rd-place groups must
// be exactly the 8 groups in the row key); prints any rows that don't validate
// so they can be cross-checked against the official FIFA Annex C.
//
// Usage: node scripts/gen-annexc.mjs /path/to/wc2026_bracket_logic.md

import { readFileSync, writeFileSync } from 'node:fs';

const src = process.argv[2] || `${process.env.HOME}/Desktop/wc2026_bracket_logic.md`;
const text = readFileSync(src, 'utf8');

// Column order of the 8 assignment columns (from the doc header).
const COLUMNS = ['M79', 'M85', 'M81', 'M74', 'M82', 'M77', 'M87', 'M80'];

const lines = text.split('\n');
const rowRe = /^\s*(\d+)\s*\|\s*([A-L\s]+?)\s*\|\s*(.+)$/;

const table = {};
const bad = [];

for (const line of lines) {
  const m = line.match(rowRe);
  if (!m) continue;
  const groupsPart = m[2].trim();
  const assignPart = m[3].split('(')[0]; // drop any "(note: …)" suffix

  const keyGroups = groupsPart.split(/\s+/).filter(Boolean);
  if (keyGroups.length !== 8) continue; // not a data row
  const key = [...keyGroups].sort().join('');

  const assigns = (assignPart.match(/3([A-L])/g) ?? []).map((t) => t[1]);
  if (assigns.length !== 8) { bad.push({ row: m[1], key, reason: `got ${assigns.length} assignments` }); continue; }

  // Validate: assigned groups must be a permutation of the key groups.
  const assignedSet = [...new Set(assigns)].sort().join('');
  if (assignedSet !== key) {
    bad.push({ row: m[1], key, reason: `assigned {${assigns.join(',')}} != key {${keyGroups.join(',')}}` });
  }

  const entry = {};
  COLUMNS.forEach((col, i) => { entry[col] = assigns[i]; });
  table[key] = entry;
}

const count = Object.keys(table).length;
console.log(`Parsed ${count} Annex C rows.`);
if (bad.length) {
  console.log(`\n⚠️  ${bad.length} rows failed validation (cross-check vs FIFA Annex C):`);
  for (const b of bad) console.log(`   row ${b.row} [${b.key}]: ${b.reason}`);
}

const out = `// AUTO-GENERATED by scripts/gen-annexc.mjs — do not edit by hand.
// 2026 World Cup Annex C: maps the set of 8 groups whose 3rd-place team qualified
// (sorted, e.g. "EFGHIJKL") to the 3rd-place GROUP that fills each variable
// Round-of-32 match. Regenerate from the source doc if the table changes.
//
// ${bad.length} source rows failed validation when generated; see scripts/gen-annexc.mjs.

export type AnnexCAssignment = Record<'M74' | 'M77' | 'M79' | 'M80' | 'M81' | 'M82' | 'M85' | 'M87', string>;

export const ANNEX_C: Record<string, AnnexCAssignment> = ${JSON.stringify(table, null, 2)};

// Keys whose source row didn't validate (assigned groups ≠ key groups). These
// are rare combinations (Group A/D among the qualifying thirds) transcribed with
// errors and could not be auto-derived (every combination has multiple valid
// matchings, so FIFA's specific choice is required). The resolver skips these at
// runtime (slots stay placeholders, API stays authoritative). Patch from the
// official FIFA Annex C, then regenerate.
export const ANNEX_C_INVALID_KEYS: string[] = ${JSON.stringify(bad.map((b) => b.key))};
`;

const dest = new URL('../lib/domain/annexC.ts', import.meta.url);
writeFileSync(dest, out);
console.log(`\nWrote ${dest.pathname} (${count} rows).`);
